[package]
name = "onebrc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
csv = {version = "1.3.0"}
mimalloc = "0.1.39"
nohash-hasher = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
tokio-stream = "0.1.15"
ustr = {version = "1.0.0", features = ["serde"] }


[dev-dependencies]
criterion = { version = "0.3", features = ["async_tokio"] }

[profile.release]
lto = true
strip = true
panic = "abort"

[[bench]]
name = "bench"
harness = false
